;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Stance.Combo2",NewTagName="Stance.Wind")
+GameplayTagRedirects=(OldTagName="Stance.Combo1",NewTagName="Stance.Fire")
+GameplayTagList=(Tag="Input.Ability.Skill1",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Heavy",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Heavy.Air",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Heavy.Air.Fire",DevComment="")hghghghgfgfgfgfgfg
+GameplayTagList=(Tag="Input.Attack.Heavy.Air.Normal",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Heavy.Air.Wind",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Heavy.Fire",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Heavy.Normal",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Heavy.Wind",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light.Air",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light.Air.Fire",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light.Air.Normal",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light.Air.Wind",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light.Fire",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light.Normal",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Light.Wind",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slam",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slam.Fire",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slam.Normal",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slam.Wind",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slash",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slash.Fire",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slash.Normal",DevComment="")
+GameplayTagList=(Tag="Input.Attack.Slash.Wind",DevComment="")
+GameplayTagList=(Tag="Stance.Fire",DevComment="")
+GameplayTagList=(Tag="Stance.Normal",DevComment="")
+GameplayTagList=(Tag="Stance.Wind",DevComment="")

